version: '3.8'

services:
  backend:
    image: pollify-backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - pollify-network
    ports:
      - target: 8000
        published: 8000
        mode: ingress
    environment:
      - DATABASE_URL=sqlite:///./polls.db
      - JWT_SECRET_KEY=your-secret-key-change-in-production
    volumes:
      - pollify-data:/app/data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    image: pollify-frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - pollify-network
    ports:
      - target: 3000
        published: 3000
        mode: ingress
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NODE_ENV=production
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

networks:
  pollify-network:
    driver: overlay
    attachable: true

volumes:
  pollify-data:
    driver: local
