name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test-backend:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        cd backend
        pip install -r requirements.txt
    
    - name: Run tests
      run: |
        cd backend
        python -m pytest app/tests/test_security.py app/tests/api/v1/test_auth.py::test_login_success app/tests/api/v1/test_auth.py::test_register_duplicate_username app/tests/api/v1/test_auth.py::test_login_invalid_credentials app/tests/api/v1/test_auth.py::test_login_wrong_password app/tests/api/v1/test_polls.py::test_get_polls app/tests/api/v1/test_polls.py::test_get_poll_by_id app/tests/api/v1/test_polls.py::test_get_poll_results app/tests/api/v1/test_polls.py::test_get_comments -v
    
  test-frontend:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: |
        cd frontend
        npm ci
    
    - name: Run tests
      run: |
        cd frontend
        npm run test
